framework:
    messenger:
        transports:
            async:
                dsn: 'doctrine://default'
                options:
                    table_name: messenger_messages
                    auto_setup: true

        routing:
            'App\Message\DataProcessorMessage': async
            'App\Message\EmailSendMessage': async
            'App\Message\UserDataSyncMessage': async
            'App\Message\PaymentProcessorMessage': async
